all:
  vars:
    ansible_user: admin
    ansible_password: cisco
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: cisco
switches:
  hosts:
    core_switch1:
      ansible_host: 192.168.2.129
